// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/device_monitor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceMonitor_GetDeviceData_FullMethodName = "/DeviceMonitor/GetDeviceData"
)

// DeviceMonitorClient is the client API for DeviceMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceMonitorClient interface {
	GetDeviceData(ctx context.Context, in *DeviceDataRequest, opts ...grpc.CallOption) (*DeviceDataResponse, error)
}

type deviceMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceMonitorClient(cc grpc.ClientConnInterface) DeviceMonitorClient {
	return &deviceMonitorClient{cc}
}

func (c *deviceMonitorClient) GetDeviceData(ctx context.Context, in *DeviceDataRequest, opts ...grpc.CallOption) (*DeviceDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceDataResponse)
	err := c.cc.Invoke(ctx, DeviceMonitor_GetDeviceData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceMonitorServer is the server API for DeviceMonitor service.
// All implementations must embed UnimplementedDeviceMonitorServer
// for forward compatibility.
type DeviceMonitorServer interface {
	GetDeviceData(context.Context, *DeviceDataRequest) (*DeviceDataResponse, error)
	mustEmbedUnimplementedDeviceMonitorServer()
}

// UnimplementedDeviceMonitorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceMonitorServer struct{}

func (UnimplementedDeviceMonitorServer) GetDeviceData(context.Context, *DeviceDataRequest) (*DeviceDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceData not implemented")
}
func (UnimplementedDeviceMonitorServer) mustEmbedUnimplementedDeviceMonitorServer() {}
func (UnimplementedDeviceMonitorServer) testEmbeddedByValue()                       {}

// UnsafeDeviceMonitorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceMonitorServer will
// result in compilation errors.
type UnsafeDeviceMonitorServer interface {
	mustEmbedUnimplementedDeviceMonitorServer()
}

func RegisterDeviceMonitorServer(s grpc.ServiceRegistrar, srv DeviceMonitorServer) {
	// If the following call pancis, it indicates UnimplementedDeviceMonitorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceMonitor_ServiceDesc, srv)
}

func _DeviceMonitor_GetDeviceData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceMonitorServer).GetDeviceData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceMonitor_GetDeviceData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceMonitorServer).GetDeviceData(ctx, req.(*DeviceDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceMonitor_ServiceDesc is the grpc.ServiceDesc for DeviceMonitor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceMonitor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DeviceMonitor",
	HandlerType: (*DeviceMonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceData",
			Handler:    _DeviceMonitor_GetDeviceData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/device_monitor.proto",
}
